server:
  port: 3333
spring:
  application:
    name: sentinel-starter
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:7777
      datasource:
        ds:
          nacos:
            server-addr: 127.0.0.1:8848
            data-id: sentinel-starter
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
      eager: true
